language: php
sudo: false
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
matrix:
  fast_finish: true
before_install:
  - composer self-update --no-progress --no-interaction
install:
  - make deps
script:
  - make test
  - if [ $(phpenv version-name) = '5.4' -o $(phpenv version-name) = '5.6' ]; then make scrutinizer; fi
notifications:
  hipchat:
    rooms:
      secure:
